/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CountdownTimer.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'CountdownTimer.view.MainViewportViewModel',
        'CountdownTimer.view.MainViewportViewController',
        'Ext.panel.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Time',
        'Ext.button.Button'
    ],

    controller: 'mainviewport',
    viewModel: {
        type: 'mainviewport'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            manageHeight: false,
            title: 'Countdown 倒计时',
            layout: {
                type: 'hbox',
                pack: 'center',
                padding: 10
            },
            items: [
                {
                    xtype: 'container',
                    //html: '{}',
                    width: 750,
                    items: [                        
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'datefield',
                                    flex: 1.5,
                                    reference: 'dateField',
                                    fieldLabel: '日期',
                                    labelAlign: 'right',
                                    labelWidth: 60,
                                    name: 'date',
                                    format: 'Y年m月d日'
                                },
                                {
                                    xtype: 'timefield',
                                    flex: 1,
                                    reference: 'timeField',
                                    //format:'G:i:s',  //格式化时间,24小时制  
                                    format:'G:i',  //格式化时间,24小时制  
                                    margin: '0 10 0 0',
                                    fieldLabel: '时间',
                                    labelAlign: 'right',
                                    labelWidth: 50
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    reference: 'startButton',
                                    margin: '0 10 0 0',
                                    text: '开始',
                                    listeners: {
                                        click: 'onStartButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    margins: '0 10 0 0',
                                    reference: 'resetButton',
                                    disabled: true,
                                    text: '重置',
                                    listeners: {
                                        click: 'onResetButtonClick'
                                    }
                                }
                            ]
                        },

                        {
                            xtype: 'container',
                            reference: 'timerDisplay',
                            height: 45,
                            margin: '0 0 20',
                            //style: '{\r    "font-size": "1.5em",\r    "border": "1px solid #ccc;",\r    "padding": "5px",\r    "text-align": "center"\r}'
                            style: 'text-align:center; font-size: 1.5em;padding:10px;'
                        },
                    ]
                }
            ]
        }
    ]

});