/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HeaderLeftContentRightFooter.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'HeaderLeftContentRightFooter.view.MainViewViewModel',
        'Ext.panel.Panel'
    ],

    viewModel: {
        type: 'mainview'
    },
    itemId: 'mainView',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            split: false,
            height: 150,
            itemId: 'headerPanel',
            title: 'Header'
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            itemId: 'centerPanel',
            title: 'Content'
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            itemId: 'leftPanel',
            width: 200,
            title: 'Left'
        },
        {
            xtype: 'panel',
            region: 'east',
            split: true,
            itemId: 'rightPanel',
            width: 200,
            title: 'Right'
        },
        {
            xtype: 'panel',
            region: 'south',
            split: false,
            height: 150,
            itemId: 'footerPanel',
            title: 'Footer'
        }
    ]

});