/*
 * File: app/model/TreeMap.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.TreeMap', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            name: 'name'
        },
        {
            name: 'description'
        },
        {
            name: 'cap'
        },
        {
            calculate: function(data) {
                return data.root ? false : !data.children;

            },
            name: 'leaf'
        },
        {
            calculate: function(data) {
                return (-5 + Math.random() * 10).toFixed(2); // percentages

            },
            name: 'change'
        },
        {
            type: 'boolean',
            defaultValue: true,
            name: 'expanded'
        }
    ]
});