/*
 * File: app/store/MyTreeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.TreeModel',
        'Ext.data.proxy.Ajax'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyTreeStore',
            autoLoad: true,
            model: 'MyApp.model.TreeModel',
            root: {
                text: 'States',
                expanded: true
            },
            proxy: me.processMyAjaxProxy({
                type: 'ajax',
                url: 'data/salary.json'
            })
        }, cfg)]);
    },

    processMyAjaxProxy: function(config) {
        config.reader= {
            type: 'salary'
        }
        return config;
    }

});