/*
 * File: app/store/TreeMap.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.TreeMap', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'MyApp.model.TreeMap',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TreeMap',
            autoLoad: true,
            model: 'MyApp.model.TreeMap',
            root: {
                expanded: true
            },
            proxy: {
                type: 'ajax',
                url: 'data/stocks.json',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});