/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('HtmlEditor.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'HtmlEditor.view.MainViewViewModel',
        'HtmlEditor.view.MainViewViewController',
        'Ext.panel.Panel',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.TaskManager'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'center',
            layout: 'fit',
            title: 'HTML Editor',
            items: [
                {
                    xtype: 'htmleditor',
                    reference: 'editor',
                    width: 150
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            action: 'submit',
                            itemId: 'submitButton',
                            text: '提交',
                            listeners: {
                                click: 'onSubmitButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            action: 'reset',
                            itemId: 'resetButton',
                            text: '重置',
                            listeners: {
                                click: 'onResetButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});