/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'MyApp.view.MainViewViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Split',
        'Ext.menu.Menu',
        'Ext.menu.Item'
    ],

    viewModel: {
        type: 'mainview'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            width: 200,
            collapsed: true,
            collapsible: true,
            title: 'West'
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'mainRegion',
            layout: 'border',
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    title: 'Messages',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'splitbutton',
                                    itemId: 'previewButton',
                                    text: 'Preview: Bottom',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                opt: 'south',
                                                checked: true,
                                                text: 'Bottom',
                                                focusable: true
                                            },
                                            {
                                                xtype: 'menuitem',
                                                opt: 'east',
                                                text: 'Right',
                                                focusable: true
                                            },
                                            {
                                                xtype: 'menuitem',
                                                opt: 'hide',
                                                frame: false,
                                                text: 'Hide',
                                                focusable: true
                                            }
                                        ]
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    split: true,
                    height: 250,
                    html: 'I am the preview pane',
                    itemId: 'previewPane',
                    minHeight: 300,
                    minWidth: 300,
                    padding: '',
                    bodyStyle: '{\r    padding: \'10px\'\r}',
                    title: 'Preview'
                }
            ]
        }
    ]

});