/*
 * File: app/view/Pack.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Pack', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.pack',

    requires: [
        'MyApp.view.PackViewModel',
        'MyApp.view.PackViewController',
        'Ext.form.Label',
        'Ext.d3.hierarchy.Pack'
    ],

    controller: 'pack',
    viewModel: {
        type: 'pack'
    },
    height: 600,
    width: 930,
    layout: 'fit',
    title: 'D3 Pack',

    items: [
        {
            xtype: 'label',
            style: 'font-size: 1.3em;',
            text: 'Please save project to see data in components.'
        },
        {
            xtype: 'd3-pack',
            store: 'PackTreeStore',
            padding: 20,
            tooltip: {
                renderer: 'onTooltip'
            }
        }
    ]

});