/*
 * File: app/view/SunBurst.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SunBurst', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sunburst',

    requires: [
        'MyApp.view.SunBurstViewModel',
        'MyApp.view.SunBurstViewController',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.d3.hierarchy.partition.Sunburst'
    ],

    controller: 'sunburst',
    viewModel: {
        type: 'sunburst'
    },
    height: 600,
    width: 930,
    layout: 'border',

    items: [
        {
            xtype: 'treepanel',
            region: 'west',
            split: true,
            width: 230,
            title: 'Folders',
            store: 'PackTreeStore',
            displayField: 'name',
            useArrows: true
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'fit',
            items: [
                {
                    xtype: 'd3-sunburst',
                    reference: 'd3',
                    store: 'PackTreeStore',
                    padding: 20,
                    tooltip: {
                        renderer: 'onTooltip'
                    }
                }
            ]
        }
    ]

});