/*
 * File: app/view/Tree.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Tree', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tree',

    requires: [
        'MyApp.view.TreeViewModel',
        'MyApp.view.TreeViewController',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.d3.hierarchy.tree.HorizontalTree',
        'Ext.d3.axis.Color'
    ],

    controller: 'tree',
    viewModel: {
        type: 'tree'
    },
    height: 600,
    width: 930,
    layout: 'border',

    items: [
        {
            xtype: 'treepanel',
            region: 'west',
            split: true,
            splitterResize: false,
            width: 230,
            collapsible: true,
            title: 'Folders',
            store: 'MyTreeStore',
            useArrows: true
        },
        {
            xtype: 'panel',
            region: 'center',
            layout: 'fit',
            title: 'Highest-paying Industries',
            items: [
                {
                    xtype: 'd3-tree',
                    nodeText: function(component, node) {
                        var text = node.data.text;

                        if (node.depth > 1) {
                            text += ' (' + Ext.util.Format.currency(node.data.salary, '$', 0) + ')';
                        }

                        return text;
                    },
                    store: 'MyTreeStore',
                    tooltip: {
                        renderer: 'onTooltip'
                    },
                    nodeRadius: 10,
                    nodeSize: [
                        20,
                        250
                    ],
                    colorAxis: {
                        field: 'id'
                    }
                }
            ]
        }
    ]

});