/*
 * File: app/model/Sale.js
 *
 * This file was generated by Sencha Architect version 4.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PivotGridExample.model.Sale', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'string',
            name: 'company'
        },
        {
            type: 'string',
            name: 'country'
        },
        {
            type: 'string',
            name: 'person'
        },
        {
            type: 'date',
            name: 'date',
            dateFormat: 'c'
        },
        {
            type: 'float',
            name: 'value'
        },
        {
            type: 'float',
            name: 'quantity'
        },
        {
            convert: function(v, rec) {
                return Ext.Date.format(rec.get('date'), "Y");
            },
            name: 'year'
        },
        {
            convert: function(v, rec) {
                return parseInt(Ext.Date.format(rec.get('date'), "m"), 10) - 1;
            },
            name: 'month'
        },
        {
            convert: function(v, rec) {
                var regions = {
                    "Belgium": 'Europe',
                    "Netherlands": 'Europe',
                    "United Kingdom": 'Europe',
                    "Canada": 'North America',
                    "United States": 'North America',
                    "Australia": 'Australia'
                };

                return regions[rec.get('country')];
            },
            name: 'continent'
        }
    ],

    init: function() {

    }

});